name: musa509week6
channels:
  - defaults
dependencies:
  - python=3.8
  - geopandas
  - pandas
  - rtree
  - psycopg2
  - sqlalchemy
  - seaborn
  - pip
  - jupyterlab
  - pip:
    - cartoframes
    - google-cloud-bigquery[pandas]
    - nb-black
